version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pgcoursemanagement
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: coursemanagement
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - springnet

  app:
    build: .
    container_name: spring-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/coursemanagement
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - springnet

volumes:
  pgdata:

networks:
  springnet:
